project:
  type: manuscript

manuscript:
  article: index.qmd
notebook-links: false
csl: iso690.csl

format:

  pdf:
    papersize: a4
    fig-cap-location: top
    toc: true
    number-sections: true
    colorlinks: false
    include-in-header: src/header.tex

execute:
  cache: true


